[project]
name = "meson-bug-14089"
version = "0.1.0"
description = "Minimal repro of mesonbuild/meson#14089"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
