name: ci

on:
  workflow_dispatch:
  pull_request_target:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - { compiler: gcc, version: 13 }
          - { compiler: intel, version: "2025.0" }
        python-version:
          - "3.8"
          - "3.13"
        meson-version:
          - "meson>1.4,<1.5"
          - "meson>1.5,<1.6"
          - "meson>1.6,<1.7"
          - "meson>1.7,<1.8"
          - "https://github.com/mesonbuild/meson/archive/1412abc516e56b7d90f36fc75acb3e4b8c294e30.zip"

    steps:
      - uses: actions/checkout@v4

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Compile and Run
        run: |
          uv venv
          uv pip install "${{ matrix.meson-version }}" meson-python ninja
          uv run meson setup build
          cd build
          uv run meson compile
          ./main_c
          ./main_f
